//Final version of the game. This one compares the names of the input with a number generated that has been converted to either Rock, Paper, or Scissors
var main = function (input) {
  console.log(">>>Start of Program");
  if (input == "") {
    var myOutputValue =
      "Let's play a game!" +
      "<br/>" +
      "Choose Rock, Paper, or Scissors, then type it into the input." +
      "<br/>" +
      "<br/>" +
      " Paper > Rock, Scissors > Paper, Rock > Scissors." +
      "<br/>" +
      "<br/>" +
      " Let's see who wins!";
  } else {
    var rNG = randomNumberGenerator();
    var convertedToItem = rngConversion(rNG);
    var myOutputValue = actualGame(input, convertedToItem);
  }
  console.log("<<<End of program");
  return myOutputValue;
};

//Generation of the number
var randomNumberGenerator = function () {
  var randomNumber = Math.random() * 3;
  var numberCleanedUp = Math.floor(randomNumber);
  console.log("RNG working. Number generated: " + numberCleanedUp);
  return numberCleanedUp;
};

//Assigning an item to each generated number
var rngConversion = function (numberCleanedUp) {
  if (numberCleanedUp == 0) {
    var generatedItem = "Rock";
  }
  if (numberCleanedUp == 1) {
    var generatedItem = "Paper";
  }
  if (numberCleanedUp == 2) {
    var generatedItem = "Scissors";
  }
  console.log("Converter working. RNGenerated item is: " + generatedItem);
  return generatedItem;
};

//The actual game code. Compares the user's input with the item name generated by randomNumberGenerator(), converted by rngConversion()
var actualGame = function (input, generatedItem) {
  console.log("Running game.");
  var user = input;
  var program = generatedItem;
  if (user == program) {
    var myOutputValue =
      "It's a draw! You chose " + input + ", and we chose " + generatedItem;
  } else if (user !== program) {
    var myOutputValue =
      "You lose! Want to try again? You chose " +
      input +
      ", and we chose " +
      generatedItem;
  }
  if (user == "Scissors" && program == "Paper") {
    var myOutputValue =
      "A WINNER IS YOU! You chose " + input + ", and we chose " + generatedItem;
  }
  if (user == "Paper" && program == "Rock") {
    var myOutputValue =
      "A WINNER IS YOU! You chose " + input + ", and we chose " + generatedItem;
  }
  if (user == "Rock" && program == "Scissors") {
    var myOutputValue =
      "A WINNER IS YOU! You chose " + input + ", and we chose " + generatedItem;
  }
  console.log("Game complete.");
  return myOutputValue;
};
