var main = function (input) {
  var sPsGameRandom = randomNumRoll();
  var myOutputValue =
    "This computer will shutdown in 5 seconds, " +
    input +
    "__cannot be used! Only scissors or paper or stone is a valid value.";

  if (
    (input == "stone" && randomNum == 1) ||
    (input == "paper" && randomNum == 2) ||
    (input == "scissors" && randomNum == 3)
  ) {
    myOutputValue = "No fight!";
  }
  if (
    (input == "stone" && randomNum == 2) ||
    (input == "paper" && randomNum == 3) ||
    (input == "scissors" && randomNum == 1)
  ) {
    myOutputValue = "You Lose!";
  }
  if (
    (input == "stone" && randomNum == 3) ||
    (input == "paper" && randomNum == 1) ||
    (input == "scissors" && randomNum == 2)
  ) {
    myOutputValue = "I lose!";
  }
  return myOutputValue;
};

var numTosPs = function () {
  var randomNum = randomNumRoll();
  //sPsRandomRoll() with the parenthesis means a var value calculated/generated by its own function, i.e not without a formulae.
  if (randomNum == 1) return "stone";
  if (randomNum == 2) return "paper";
  if (randomNum == 3) return "scissors";
  //return randomNum;??
};

var randomNumRoll = function () {
  var randomDecimal = Math.random() * 4;
  var randomInteger = Math.floor(randomDecimal);
  return randomInteger;
};
