var userWin = 0;
var userAttempt = 0;
var userWinningPercentage = 0;

var main = function (input) {
  var randomSPS = randomSPSoutput();
  console.log("random guess generated by Computer:");
  console.log(randomSPS);

  // Its a draw,
  // IF input == random output

  if (input == randomSPS) {
    userAttempt += 1;
    userWinningPercentage = (userWin / userAttempt) * 100;
    userWinningPercentage = userWinningPercentage.toFixed(1);
    return `It's a tie! <br> <br> Your guess: ${input}; <br> Computer guess: ${randomSPS} <br><br> You have attempted ${userAttempt} times and won ${userWin} times (${userWinningPercentage}%) ! <br><br> Type "scissors", "paper" or "stone" to play another round!`;
  }

  // You win,
  // IF input == scissors && random output == paper
  // OR input == paper && random output == rock
  // OR input == rock && random output == scissors

  if (
    (input == "scissors" && randomSPS == "paper") ||
    (input == "paper" && randomSPS == "stone") ||
    (input == "stone" && randomSPS == "scissors")
  ) {
    userAttempt += 1;
    userWin += 1;
    userWinningPercentage = (userWin / userAttempt) * 100;
    userWinningPercentage = userWinningPercentage.toFixed(1);
    return `You win! <br> <br> Your guess: ${input}; <br> Computer guess: ${randomSPS} <br><br> You have attempted ${userAttempt} times and won ${userWin} times (${userWinningPercentage}%) ! <br><br> Type "scissors", "paper" or "stone" to play another round!`;
  }

  // You lose,
  // IF input == scissors && random output == rock
  // OR input == paper && random output == scissors
  // OR input == rock && random output == paper

  if (
    (input == "scissors" && randomSPS == "stone") ||
    (input == "paper" && randomSPS == "scissors") ||
    (input == "stone" && randomSPS == "paper")
  ) {
    userAttempt += 1;
    userWinningPercentage = (userWin / userAttempt) * 100;
    userWinningPercentage = userWinningPercentage.toFixed(1);
    return `You lose! <br> <br> Your guess: ${input}; <br> Computer guess: ${randomSPS} <br><br> You have attempted ${userAttempt} times and won ${userWin} times (${userWinningPercentage}%) ! <br><br> Type "scissors", "paper" or "stone" to play another round!`;
  }

  // Starting page / When user input wrongly

  var myOutputValue = `~ Game Instructions ~ <br><br> There are only 3 input options: <br><br> "scissors", "paper", and "stone". <br><br> Try input and beat the computer!`;

  return myOutputValue;
};

// create 3 random number (0,1,2) and let them represents scissors, paper, stone respectively

var randomSPSoutput = function () {
  var randomise = Math.floor(Math.random() * 3);

  if (randomise == 0) {
    return "scissors";
  }
  if (randomise == 1) {
    return "paper";
  }
  return "stone";
};
